import {renderMarkdown} from './renderer.js';
const $ = s => document.querySelector(s);
const view = $('#view');
let token = sessionStorage.getItem('kc-workbench-token') || '', overview = null, currentView = 'inbox', epoch = 0;
let exportURL = null, exportGeneration = 0;
function clearExport(){exportGeneration++;if(exportURL){URL.revokeObjectURL(exportURL);exportURL=null;}document.getElementById('prepared-export')?.remove();}
const labels = {added:'已入库',duplicate:'内容重复',rejected:'未收录',analysis_failed:'整理失败',reserved:'等待入库',fetching:'正在读取',pending:'待处理',queued:'已接收',running:'正在处理',complete:'已完成',partial:'部分完成',failed:'失败',skipped:'未执行',no_new:'没有新增',no_results:'没有结果',needs_review:'待核实',needs_refresh:'需更新',watching:'观察中',candidate:'可能感兴趣',followed:'已关注',paused:'已暂停',closed:'已关闭',confirmed:'已确认',unknown:'未知',stale:'已过期',open:'未处理',acknowledged:'已读',dismissed:'已忽略',interrupted:'已中断'};
function node(tag, text='', cls='') {const e=document.createElement(tag); if(text!==null)e.textContent=text; if(cls)e.className=cls; return e;}
function append(parent,...children){children.flat().forEach(c=>{if(c)parent.append(c);});return parent;}
function message(text,error=false){const box=$('#global-status');box.hidden=!text;box.textContent=text;box.className='notice'+(error?' error':'');if(error&&text){box.tabIndex=-1;box.focus();box.scrollIntoView({block:'nearest'});}}
function report(error){message(error.message||'操作未完成，请查看任务记录。',true);}
function button(text,fn,cls=''){const b=node('button',text,cls);b.type='button';b.addEventListener('click',()=>busy(b,fn));return b;}
async function busy(control,fn){control.disabled=true;control.setAttribute('aria-busy','true');try{await fn();}catch(error){report(error);}finally{control.disabled=false;control.removeAttribute('aria-busy');}}
function badge(value){return node('span',labels[value]||value||'未执行','badge '+(['failed'].includes(value)?'error':['partial','needs_review','needs_refresh','stale','unknown'].includes(value)?'warning':value==='complete'?'good':''));}
function when(value){if(!value)return '尚未记录';const d=new Date(typeof value==='number'?value*1000:value);return Number.isNaN(+d)?value:d.toLocaleString('zh-CN',{hour12:false});}
function empty(text){return node('div',text,'empty');}
function field(form,label,name,{type='text',value='',hint='',required=false,multiline=false}={}){const wrap=node('div',null,'field'),id='field-'+Math.random().toString(36).slice(2);const lab=node('label',label);lab.htmlFor=id;const input=node(multiline?'textarea':'input');input.id=id;input.name=name;input.value=value??'';if(!multiline)input.type=type;input.required=required;append(wrap,lab,input);if(hint){const help=node('p',hint,'hint');help.id=id+'-help';input.setAttribute('aria-describedby',help.id);wrap.append(help);}form.append(wrap);return input;}
function formSubmit(form,label,fn,primary=true){const submit=node('button',label,primary?'primary':'');submit.type='submit';form.append(submit);form.addEventListener('submit',event=>{event.preventDefault();busy(submit,()=>fn(new FormData(form)));});return submit;}
function header(title,description,action){const h=node('header',null,'page-head'),text=node('div');append(text,node('h1',title),node('p',description));append(h,text,action);view.append(h);}
async function request(path,{raw=false,...options}={}){const response=await fetch(path,{...options,headers:{'Authorization':'Bearer '+token,...(options.body?{'Content-Type':'application/json'}:{}),...options.headers},credentials:'omit',redirect:'error'});if(!response.ok){let body;try{body=await response.json();}catch{}const detail=body?.error;const error=new Error(typeof detail==='string'?detail:detail?.message||`请求未完成（${response.status}）`);error.code=typeof detail==='object'?detail?.code:null;error.status=response.status;throw error;}return raw?response:response.json();}
async function loadOverview(){overview=await request('/api/overview');return overview;}
async function go(name){clearExport();const mine=++epoch;currentView=name;view.replaceChildren(node('p','正在读取…','muted'));message('');document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-current',b.dataset.view===name?'page':'false'));try{await loadOverview();if(mine!==epoch)return;view.replaceChildren();await ({inbox:inboxView,library:libraryView,interests:interestsView,wiki:wikiView,context:contextView,settings:settingsView}[name])();$('#main').focus();}catch(error){if(mine===epoch){view.replaceChildren(empty('未能读取工作台。请检查服务连接后重试。'),button('重试',()=>go(name)));report(error);}}}
async function action(action,args={}){const job=await request('/api/actions',{method:'POST',body:JSON.stringify({action,...args})});if(!job.id)return job.result;return watch('/api/actions/'+job.id,job);}
async function watch(path,initial){let job=initial;message('已接收，正在等待处理结果…');for(let i=0;i<180;i++){if(!['queued','running'].includes(job.status)){if(job.status==='failed')throw new Error(job.error?.message||'任务失败，请查看记录。');const outcome=jobOutcome(job);message(outcome.text,outcome.warning);return job.result||job;}await new Promise(resolve=>setTimeout(resolve,1500));if(!token)throw new Error('已退出连接。任务可在重新连接后查看。');job=await request(path);}message('任务仍在处理，已保留记录。可稍后刷新收件箱查看。');return {status:'running'};}
async function doAction(name,args){const result=await action(name,args);await go(currentView);if(name==='wiki-build'&&result?.status==='needs_review')message('候选版本已生成，人工编辑内容未被覆盖。请在知识 Wiki 查看候选。');return result;}
async function download(path,name){clearExport();const pageEpoch=epoch, generation=exportGeneration;const response=await request(path,{raw:true});const blob=await response.blob();if(pageEpoch!==epoch||generation!==exportGeneration||!token)return;exportURL=URL.createObjectURL(blob);const prepared=node('section',null,'notice');prepared.id='prepared-export';const link=node('a','保存 ZIP 文件');link.href=exportURL;link.download=name;append(prepared,node('p','导出已准备，请点击保存 ZIP 文件。'),link);view.prepend(prepared);message('导出已准备，尚未确认文件已下载。');link.focus();}
function sectionErrors(key){if(overview.errors?.[key])view.append(node('p',overview.errors[key].message,'notice error'));if(overview.has_more?.[key])view.append(node('p',`当前展示前 100 项，共 ${overview.totals[key]} 项。`,'hint'));}
function row(title,description,actions=[],state){const r=node('article',null,'row'),main=node('div',null,'row-main');append(main,typeof title==='string'?node('h3',title):title,description?node('p',description,'meta'):null,state?badge(state):null);append(r,main,append(node('div',null,'toolbar'),...actions));return r;}
function inferenceDetail(item){const names={complete:'已完成',failed:'失败',partial:'部分完成',skipped:'未执行',insufficient_sources:'独立资料不足，尚未归纳',running:'正在处理',needs_review:'待核实'};const reasons={invalid_citation:'引用校验未通过',invalid_inference:'归纳结果校验未通过',invalid_subtopics:'细分主题校验未通过',inputs_changed:'输入资料已变化',input_too_large:'输入超过限制',already_attempted:'相同输入已有运行记录，需检查后处理',configuration_missing:'模型尚未配置',inference_failed:'归纳未完成'};const code=item?.error_code||item?.error?.code;const reason=reasons[code];return (names[item?.status]||'状态待核实')+(reason?' · '+reason:'');}
function analysisOutcome(result){const prefix=result?.status==='partial'?'AI 整理部分完成':'AI 整理已保存';return result?.interest_inference?prefix+'；兴趣归纳：'+inferenceDetail(result.interest_inference)+'。当前展示可用整理结果。':prefix+'，当前展示可用整理结果。';}
function jobOutcome(job){
 const result=job.result||{},problem=status=>['failed','partial','needs_review','interrupted'].includes(status);
 const stages=['capture','analysis','interest_inference','wiki','alerts'];
 const warning=problem(job.status)||problem(result.status)||stages.some(stage=>problem(result[stage]?.status));
 if(result.capture||result.analysis||result.wiki||result.alerts){
  const names={capture:'原文采集',analysis:'AI 整理',interest_inference:'兴趣归纳',wiki:'Wiki 更新',alerts:'背景关联'};
  const state=warning&&job.status==='complete'?'partial':job.status;
  const parts=['本次处理：'+(labels[state]||'状态待核实')];
  for(const stage of stages){const item=result[stage];if(item)parts.push(names[stage]+'：'+(stage==='interest_inference'?inferenceDetail(item):(labels[item.status]||'状态待核实')));}
  return {text:parts.join('；')+'。',warning};
 }
 return {text:result.interest_inference?analysisOutcome(result):(labels[job.status]||'处理结束'),warning};
}
function detailList(job){const details=node('details'),summary=node('summary','处理详情');details.append(summary);const result=job.result||{},dl=node('dl',null,'task-details');for(const stage of ['capture','analysis','interest_inference','wiki','alerts']){if(!result[stage])continue;append(dl,node('dt',({capture:'原文采集',analysis:'AI 整理',interest_inference:'兴趣归纳',wiki:'Wiki 更新',alerts:'背景关联'})[stage]),node('dd',stage==='interest_inference'?inferenceDetail(result[stage]):`${labels[result[stage].status]||result[stage].status||'有结果'}${result[stage].reason?' · '+result[stage].reason:''}${result[stage].error?.message?' · '+result[stage].error.message:''}`));}if(job.error)append(dl,node('dt','失败原因'),node('dd',job.error.message||job.error.code));for(const warning of result.warnings||[])dl.append(node('dd',warning));append(details,dl,node('p','任务编号：'+job.id,'meta'));return details;}
async function inboxView(){header('收件箱','保存看到的内容，随后在这里查看每一步的真实结果。',button('刷新',()=>go('inbox')));const form=node('form',null,'panel form-narrow');field(form,'网页或视频链接','url',{type:'url',required:true,hint:'公众号、视频需配置可用读取服务；不能保证每个链接都能取得正文。'});field(form,'收藏意图（选填）','note',{multiline:true});formSubmit(form,'添加到知识库',async data=>{const initial=await request('/api/captures',{method:'POST',body:JSON.stringify({url:data.get('url'),note:data.get('note'),origin:'user'})});form.reset();await watch('/api/captures/'+initial.id,initial);await go('inbox');});view.append(form);const entry=node('details');append(entry,node('summary','从浏览器和微信添加'),node('p','Chrome / Edge 插件支持当前网页和链接右键采集。微信文章可先在浏览器打开再采集；微信消息桥尚未部署，不能直接读取或转发你的聊天记录。','hint'));view.append(entry);view.append(node('h2','最近任务'));const jobs=overview.inbox_jobs||[];if(!jobs.length)view.append(empty('还没有提交链接。先添加一条你想保留的资料。'));for(const job of jobs){const capture=job.result?.capture||job.result;const matching=(overview.sources||[]).find(s=>s.id===capture?.source_id);const r=row(capture?.title||matching?.title||'链接采集',job.url||capture?.original_url||capture?.url||'提交的链接正在处理中',capture?.source_id?[button('阅读资料',()=>openSource(capture.source_id))]:[],job.status);append(r.firstChild,node('p',when(job.created_at)+(job.note?' · '+job.note:''),'hint'),detailList(job));view.append(r);}if(overview.action_jobs?.length){const details=node('details');details.append(node('summary','整理与检索任务'));for(const job of overview.action_jobs){const r=row(({analyze:'整理资料','wiki-build':'更新 Wiki',discover:'主动检索','alerts-check':'关联检查','search-web':'搜索验证'})[job.action]||job.action,'',[],job.status);r.firstChild.append(detailList(job));details.append(r);}view.append(details);}}
async function libraryView(){
 header('知识库','查找原文、关联笔记与知识修订。启用向量模型并建立索引后支持语义检索。',button('导出知识库',()=>download('/api/export/library','知识库备份.zip')));
 const vault=overview.vault_sync||{status:'not_synced',message:'尚未生成Obsidian阅读镜像。'},mirror=node('section',null,vault.status==='failed'?'notice error':'notice');
 const mirrorState=node('p',vault.message);mirrorState.setAttribute('aria-live','polite');
 const mirrorRetry=button(vault.status==='failed'?'重试同步':vault.status==='not_synced'?'生成阅读镜像':'重新同步',async()=>{try{await action('vault-sync');}finally{if(currentView==='library')await go('library');}});
 append(mirror,node('h2','Obsidian阅读镜像'),mirrorState,mirrorRetry);view.append(mirror);

 const mine=epoch,form=node('form',null,'toolbar');field(form,'搜索内容','query',{required:true});
 const list=node('div'),state=node('p','','hint');state.setAttribute('aria-live','polite');
 let activeQuery='',nextCursor=null,loading=false,shown=0;const seen=new Set();
 const more=button('下一页',()=>loadPage(false)),reload=button('重新读取',()=>loadPage(true));more.hidden=true;reload.hidden=true;
 const submit=formSubmit(form,'搜索',async data=>{if(loading)return;activeQuery=data.get('query').trim();await loadPage(true);});
 async function loadPage(reset){
  if(loading||(!reset&&!nextCursor))return;
  loading=true;submit.disabled=true;more.disabled=true;reload.disabled=true;
  const params=new URLSearchParams({limit:'100'});if(activeQuery)params.set('query',activeQuery);if(!reset)params.set('cursor',nextCursor);
  try{
   const result=await request('/api/v1/knowledge?'+params.toString());if(mine!==epoch)return;
   if(reset){seen.clear();shown=0;list.replaceChildren();}
   const records=(result.results||[]).filter(record=>{if(seen.has(record.record_id))return false;seen.add(record.record_id);return true;});
   renderKnowledge(list,records,!reset);shown+=records.length;nextCursor=result.next_cursor||null;more.hidden=!nextCursor;reload.hidden=true;
   const retrieval=result.retrieval,mode=retrieval?.mode||'';let description='';
   if(activeQuery){description=mode.startsWith('hybrid')?'已使用语义与关键词检索。':'已使用关键词检索。';if(mode.includes('rerank'))description+='已对候选进行重排。';if(retrieval?.degraded)description+='部分增强能力不可用，请检查配置或重建索引。';if(retrieval?.candidate_truncated)description+='当前只展示候选上限内的结果。';}
   state.textContent=description+`已显示 ${shown} 项，共 ${result.total??shown} 项。`;
  }catch(error){
   if(mine!==epoch)return;
   if(error.code==='cursor_stale'){nextCursor=null;more.hidden=true;reload.hidden=false;state.textContent='分页期间知识或检索结果已变化。请点击“重新读取”，从第一页获取当前结果。';}
   else throw error;
  }finally{loading=false;submit.disabled=false;more.disabled=false;reload.disabled=false;}
 }
 append(view,form,state,list,append(node('div',null,'toolbar'),more,reload));await loadPage(true);
}
function renderKnowledge(container,records,appendRows=false){if(!appendRows)container.replaceChildren();if(!records.length){if(!appendRows)container.append(empty('还没有匹配的资料。可以回到收件箱添加链接。'));return;}for(const record of records){const read=()=>openRecord(record.record_id);container.append(row(button(record.title||'未命名资料',read,'source-link'),record.excerpt,[button('阅读',read)],record.stale?'stale':record.status==='expired'?'stale':null));}}
async function openRecord(id){
 const data=await request('/api/v1/knowledge/'+id);if(data.kind==='source')return openSource(id,data.version_id);
 clearExport();++epoch;view.replaceChildren();header(data.metadata.title,data.stale?'所引用来源已有变化，请核实。':'知识修订 · '+(data.metadata.status==='expired'?'已过期':'有效'),button('返回知识库',()=>go('library')));
 const content=node('div',null,'reading');view.append(content);await markdownInto(data.markdown,content,data.kind==='source_overlay'?{sourceId:id,version:data.source_version}:{});
 for(const ref of data.metadata.references||[]){if(ref.source_id)view.append(button('阅读所引用版本',()=>openSource(ref.source_id,ref.version_id)));}
}
function renderSources(container,sources){container.replaceChildren();if(!sources.length){container.append(empty('还没有匹配的资料。可以回到收件箱添加链接。'));return;}for(const source of sources){const id=source.id||source.source_id;container.append(row(button(source.title||'未命名资料',()=>openSource(id),'source-link'),source.excerpt||source.url,[button('阅读',()=>openSource(id))]));}}
function sourceBody(markdown){return String(markdown||'').replace(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/,'');}
async function markdownInto(text,container,options={}){await renderMarkdown(text||'',container,{request,...options});}
async function evidencePanel(data,container,anchor){container.replaceChildren();append(container,node('h2','精确来源证据'),node('p','以下为生成时保存的历史原文；不会替换成当前版本。','hint'));const excerpt=node('div',null,'reading');container.append(excerpt);await markdownInto((data.evidence_markdown||'').replace(/^<a id="[A-Za-z0-9_.:-]+"><\/a>\s*$/gm,''),excerpt,{sources:data.sources});if(anchor){const heading=[...excerpt.querySelectorAll('h1,h2,h3')].find(h=>h.textContent===anchor);if(heading){heading.tabIndex=-1;heading.focus();heading.scrollIntoView({block:'start'});}}for(const [sid,source]of Object.entries(data.sources||{})){const details=node('details');append(details,node('summary',(source.metadata?.title||'来源')+' · '+source.version_id));const body=node('div',null,'reading');details.append(body);let loaded=false;details.addEventListener('toggle',()=>{if(details.open&&!loaded){loaded=true;markdownInto(sourceBody(source.markdown),body,{sourceId:sid,version:source.version_id,sources:data.sources}).catch(report);}});container.append(details);}}
async function openSource(id,version){clearExport();++epoch;view.replaceChildren(node('p','正在读取资料…'));try{const data=await request('/api/sources/'+id+(version?'/versions/'+version:'')),source=data.source,meta=source.metadata,analysis=data.latest_analysis;view.replaceChildren();header(meta.title||'资料阅读','采集于 '+when(meta.captured_at),button('返回知识库',()=>go('library')));const provenance=node('div',null,'toolbar');provenance.append(badge(meta.status));try{const original=new URL(meta.original_url);if(['http:','https:'].includes(original.protocol)&&!original.username&&!original.password){const link=node('a','打开原始来源');link.href=original.href;link.target='_blank';link.rel='noopener noreferrer';provenance.append(link);}}catch{}const versionDetails=node('details');append(versionDetails,node('summary','来源版本信息'),node('p',`来源 ${id} · 版本 ${meta.version_id}`,'hint'));append(view,provenance,versionDetails);const tools=node('div',null,'toolbar');append(tools,button('重新整理',async()=>{const result=await action('analyze',{identifier:id});if(result?.status==='running')return;await openSource(id);message(analysisOutcome(result),['failed','partial','needs_review'].includes(result?.interest_inference?.status));}),button('下载原文与图片',()=>download('/api/export/source/'+id+'/'+meta.version_id,'资料.zip')));if(analysis)tools.append(button('下载整理',()=>download('/api/export/analysis/'+analysis.record.id,'整理与证据.zip')));if(data.is_current_knowledge_evidence===false){tools.querySelector('button').disabled=true;const reason=data.knowledge_authority?.reason;view.append(node('p',reason==='knowledge_expired'?'该知识已标为过期。历史原文仍可阅读，不再用于自动整理或主题证据。':reason==='knowledge_revised'?'该知识已有维护修订。这里展示原始证据；当前修订请从知识库阅读。':'这里展示历史或待核实证据，不能作为当前自动整理输入。','notice'));}view.append(tools);if(data.analysis_stale||analysis?.stale)view.append(node('p','整理所用来源已变化，请核实历史证据或重新整理。','notice'));if(!analysis)view.append(node('p','当前版本尚未完成 AI 整理，正在展示原文。','hint'));const tabs=node('div',null,'tabs'),content=node('div',null,'reading'),evidence=node('section',null,'section-gap');view.append(tabs,content,evidence);const render=async mode=>{content.hidden=mode==='evidence';evidence.replaceChildren();for(const b of tabs.children)b.setAttribute('aria-pressed',String(b.dataset.mode===mode));if(mode==='evidence'){content.replaceChildren();await evidencePanel(analysis,evidence);return;}await markdownInto(mode==='analysis'?analysis.markdown:sourceBody(source.markdown),content,{sourceId:id,version:meta.version_id,sources:analysis?.sources,onSource:()=>render('source').catch(report),onEvidence:analysis?anchor=>evidencePanel(analysis,evidence,anchor).catch(report):undefined});};for(const [mode,title]of [['source','完整原文'],...(analysis?[['analysis','AI 整理'],['evidence','引用证据']]:[])]){const b=button(title,()=>render(mode));b.dataset.mode=mode;tabs.append(b);}await render(analysis&&!data.analysis_stale?'analysis':'source');$('#main').focus();}catch(error){report(error);}}
async function interestsView(){header('关注主题','最近 30 天的三篇独立资料会产生兴趣候选。只有你明确关注，系统才会主动检索。',button('刷新',()=>go('interests')));sectionErrors('interests');if(!overview.interests?.length)view.append(empty('还没有主题。先采集并整理资料，系统会在这里展示推测依据。'));for(const topic of overview.interests||[]){const actions=[button(topic.state==='followed'?'继续观察':'关注',()=>doAction('interest-set',{identifier:topic.id,state:topic.state==='followed'?'watching':'followed'})),button('暂停',()=>doAction('interest-set',{identifier:topic.id,state:'paused'})),button('关闭',()=>doAction('interest-set',{identifier:topic.id,state:'closed'}))];if(topic.eligible_for_discovery){actions.push(button('检索一次',async()=>{const result=await action('discover',{identifier:topic.id});await go('interests');showDiscovery(result);}));}const r=row(topic.name,`${topic.user_source_count} 篇独立用户资料`,actions,topic.state);const detail=node('details');detail.append(node('summary','查看判断依据'));for(const e of topic.evidence||[])append(detail,button(e.title||'资料',()=>openSource(e.source_id,e.version_id),'link'),node('p',e.reason,'hint'));r.firstChild.append(detail);if(topic.eligible_for_discovery){const schedule=(overview.schedules||[]).find(s=>s.topic_id===topic.id),f=node('form',null,'section-gap');const hours=field(f,'检索间隔（小时）','hours',{type:'number',value:schedule?schedule.interval_seconds/3600:24});hours.min=1;hours.max=720;formSubmit(f,schedule?.enabled?'保存检索间隔':'启用定时检索',d=>doAction('schedule-set',{identifier:topic.id,interval_hours:Number(d.get('hours')),enabled:true}),false);if(schedule?.enabled)f.append(button('暂停计划',()=>doAction('schedule-set',{identifier:topic.id,enabled:false})));append(f,node('p',schedule?.enabled?'下次到期：'+when(schedule.next_due):'尚未启用定时检索。','hint'));r.firstChild.append(f);}view.append(r);}view.append(node('p',overview.capabilities?.scheduler_running?'定时工作进程正在运行。':'定时工作进程未运行。保存计划不代表已经执行。','notice'));}
function showDiscovery(result){if(!result||result.status==='running')return;const section=node('section',null,'panel section-gap');append(section,node('h2','本次检索结果'),badge(result.status));for(const candidate of result.candidates||[]){let reason=candidate.reason||'',citations=[];if(typeof reason==='string'){try{const parsed=JSON.parse(reason);if(parsed&&typeof parsed==='object'){reason=typeof parsed.reason==='string'?parsed.reason:'已完成候选筛选。';citations=Array.isArray(parsed.evidence)?parsed.evidence:[];}}catch{}}else if(reason&&typeof reason==='object'){citations=Array.isArray(reason.evidence)?reason.evidence:[];reason=typeof reason.reason==='string'?reason.reason:'';}const item=node('div',null,'row-main section-gap');append(item,node('h3',candidate.title||candidate.url),badge(candidate.status),node('p',String(reason||candidate.error_code||''),'hint'));if(citations.length){const details=node('details');details.append(node('summary','查看筛选依据'));for(const cite of citations){if(typeof cite.quote==='string')append(details,node('p',cite.quote),node('p',`原文第 ${cite.start_line}–${cite.end_line} 行`,'hint'));}item.append(details);}if(candidate.source_id)item.append(button('阅读资料',()=>openSource(candidate.source_id),'link'));section.append(item);}view.prepend(section);}
async function wikiView(){header('知识 Wiki','把资料组织成可追溯的主题知识；引用匹配不等于结论已被独立证实。',button('刷新',()=>go('wiki')));sectionErrors('wikis');for(const page of overview.wikis||[]){view.append(row(page.record?.name||page.record?.topic_name||(overview.interests||[]).find(t=>t.id===page.topic_id)?.name||'主题 Wiki',page.stale?'来源已变化，需要重新更新。':'来源版本未发现变化。',[button('阅读',()=>openWiki(page.topic_id)),button('更新',()=>doAction('wiki-build',{identifier:page.topic_id})),button('下载',()=>download('/api/export/wiki/'+page.topic_id,'主题Wiki.zip'))],page.stale?'needs_refresh':page.modified?'needs_review':'complete'));}if(!overview.wikis?.length)view.append(empty('还没有 Wiki。整理资料产生主题后，可以选择下面的主题生成。'));const topics=overview.interests||[];if(topics.length){const form=node('form',null,'panel section-gap'),lab=node('label','选择主题');const select=node('select');select.id='wiki-topic';lab.htmlFor=select.id;select.name='topic';topics.forEach(t=>{const o=node('option',t.name);o.value=t.id;select.append(o);});append(form,lab,select);formSubmit(form,'生成或更新 Wiki',d=>doAction('wiki-build',{identifier:d.get('topic')}));view.append(form);}const candidates=(overview.action_jobs||[]).filter(j=>j.result?.status==='needs_review'&&j.result.topic_id);if(candidates.length){view.append(node('h2','保留人工内容的候选'));for(const job of candidates)view.append(row('待审阅版本','人工编辑页面未被覆盖。候选可读；自动合并尚未提供。',[button('阅读候选',()=>openWiki(job.result.topic_id,job.result.version_id))],'needs_review'));}}
async function openWiki(id,version){clearExport();++epoch;const data=await request('/api/wiki/'+id+(version?'/versions/'+version:''));view.replaceChildren();header(data.record?.name||'主题 Wiki',data.stale?'此页所用来源已有变化。':'主题综合与证据',button('返回 Wiki',()=>go('wiki')));const content=node('div',null,'reading'),evidence=node('section',null,'section-gap');append(view,button('查看来源证据',()=>evidencePanel(data,evidence)),content,evidence);await markdownInto(data.markdown.replace(/\]\(\.\.\/versions\/interest_[a-f0-9]{24}\/[a-f0-9]{32}\/evidence\.md#/g,'](evidence.md#'),content,{sources:data.sources,onSource:(sid,ver)=>openSource(sid,ver),onEvidence:anchor=>evidencePanel(data,evidence,anchor).catch(report)});}
async function contextView(){header('背景与提醒','记录你的实际情况，让资料与设备、项目产生有依据的关联。系统不会替你执行升级。',button('刷新',()=>go('context')));const form=node('form',null,'panel form-narrow');append(form,node('h2','记录一项背景'));field(form,'设备或项目','subject',{required:true});field(form,'属性','field',{required:true,hint:'例如系统版本、部署位置或项目约束。不要填写密码和密钥。'});field(form,'当前值','value');const unknown=node('input');unknown.type='checkbox';unknown.name='unknown';const label=node('label',null,'inline-check field');append(label,unknown,document.createTextNode('目前未知，需要核实'));form.append(label);const days=field(form,'有效天数','days',{type:'number',value:30});days.min=1;days.max=3650;formSubmit(form,'保存背景',d=>doAction('context-set',{subject:d.get('subject'),field:d.get('field'),value:d.get('value'),status:d.get('unknown')?'unknown':'confirmed',valid_days:Number(d.get('days'))}));view.append(form);sectionErrors('facts');for(const f of overview.facts||[])view.append(row(f.subject+' · '+f.field,(f.value||'尚未确认')+' · 确认于 '+when(f.confirmed_at)+' · '+f.valid_days+'天有效',[],f.status));view.append(node('h2','关联提醒','section-gap'));const check=node('form',null,'panel');const labelSelect=node('label','选择用于关联分析的资料（可多选，最多12篇）'),select=node('select');select.id='alert-sources';labelSelect.htmlFor=select.id;select.name='sources';select.multiple=true;select.size=4;(overview.sources||[]).forEach(s=>{const o=node('option',s.title);o.value=s.id;select.append(o);});append(check,labelSelect,select,node('p','选中资料与显式背景将发送给配置的模型；提醒仍需人工核实。','hint'));formSubmit(check,'检查关联',d=>{const ids=d.getAll('sources');if(!ids.length||ids.length>12)throw new Error('请选择1至12篇资料。');return doAction('alerts-check',{source_ids:ids});},false);view.append(check);sectionErrors('alerts');if(!overview.alerts?.length)view.append(empty('当前没有提醒。这不代表已经证明不存在风险。'));for(const a of overview.alerts||[]){const r=row(a.title,a.detail,[button('依据',()=>openAlert(a.run_id)),...['acknowledged','dismissed','open'].map(state=>button(labels[state],()=>doAction('alerts-set',{identifier:a.id,state})))],a.status);append(r.firstChild,node('p','背景：'+(labels[a.context_status]||[...new Set((overview.facts||[]).filter(f=>(a.fact_ids||[]).includes(f.id)).map(f=>labels[f.status]||f.status))].join('、')||'待核实')+' · 处理：'+(labels[a.feedback_state]||'未处理'),'hint'),node('p','建议：'+a.suggested_action));view.append(r);}}
async function openAlert(id){clearExport();++epoch;const data=await request('/api/alerts/'+id);view.replaceChildren();header('提醒与依据',data.stale?'背景或资料已变化，请重新核实。':'模型候选，尚未独立确认适用性。',button('返回提醒',()=>go('context')));const content=node('div',null,'reading'),evidence=node('section',null,'section-gap');append(view,content,evidence);await markdownInto(data.markdown,content,{sources:data.sources,onEvidence:anchor=>evidencePanel(data,evidence,anchor).catch(report)});view.append(button('展开精确引用',()=>evidencePanel(data,evidence)));}
function choice(form,label,name,items,value){const wrap=node('div',null,'field'),lab=node('label',label),select=node('select');select.name=name;select.id='select-'+name;lab.htmlFor=select.id;for(const [v,t]of items){const option=node('option',t);option.value=v;select.append(option);}select.value=value;append(wrap,lab,select);form.append(wrap);return select;}
function engineState(engine){
 const labels={not_configured:'尚未配置',configured:'已保存，待自动识别',adapted:'接口已识别',unsupported:'暂未识别此服务',failed:'连接未完成'};
 return labels[engine?.status]||'尚未配置';
}
function engineForm(settings,kind,title,description){
 const engine=settings.engines?.[kind]||{},form=node('form',null,'panel form-narrow');
 form.dataset.engine=kind;
 append(form,node('h2',title),node('p',description,'hint'));
 const state=node('p',engineState(engine),'engine-state');state.setAttribute('role','status');form.append(state);
 if(engine.message&&engine.message!==engineState(engine))form.append(node('p',engine.message,'hint'));
 choice(form,'连接方式',kind+'-transport',[['api','API'],['mcp','MCP']],engine.transport||'api');
 field(form,'服务地址','endpoint',{type:'url',required:true,value:engine.endpoint||'',hint:'填写引擎提供的地址，系统自动识别接口。'});
 const key=field(form,'密钥（如需要）','api_key',{type:'password',hint:engine.key_configured?'已保存；地址不变时留空保留。密钥不会回显。':'无需密钥的服务可留空。'});key.autocomplete='new-password';
 const save=formSubmit(form,'保存并自动识别',async data=>{
  await action('settings-engine',{kind,transport:data.get(kind+'-transport'),endpoint:data.get('endpoint').trim(),api_key:data.get('api_key')});
  key.value='';
  try{
   const result=await action('settings-engine-discover',{kind});
   await go('settings');
   if(result?.status==='running'){message('服务已保存，接口识别仍在进行。稍后可刷新此页查看。');return;}
   const current=result?.engines?.[kind]||overview.settings?.engines?.[kind];
   const ok=current?.status==='adapted';
   message(ok?'接口已识别。实际采集结果会在收件箱中记录。':current?.message||'服务已保存，但系统尚未完成接口识别。',!ok);
  }catch(error){await go('settings');report(error);}
 });
 if(settings.explicit_providers_override){save.disabled=true;form.append(node('p','当前服务由启动配置管理。','notice'));}
 return form;
}
async function settingsView(){
 const settings=overview.settings||await request('/api/settings');
 header('三类引擎','你提供引擎，系统负责接口适配、链接分流和内容处理。');
 const model=node('form',null,'panel form-narrow');model.dataset.engine='llm';
 append(model,node('h2','LLM'),node('p','识别有效内容、清洗资料，归纳兴趣并整理知识 Wiki。','hint'),node('p',settings.model?.configured?'已配置':'尚未配置','engine-state'));
 if(settings.model?.source==='environment')model.append(node('p','当前使用启动环境中的模型设置。','notice'));
 field(model,'服务地址','base_url',{type:'url',value:settings.model?.base_url,required:true});
 field(model,'模型','model',{value:settings.model?.model,required:true});
 const key=field(model,'密钥','api_key',{type:'password',hint:settings.model?.key_configured?'已保存；留空保留，密钥不会回显。':'仅保存在本机受保护设置中。'});key.autocomplete='new-password';
 formSubmit(model,'保存 LLM',async data=>{
  await action('settings-model',{...Object.fromEntries(data),timeout_seconds:settings.model?.timeout_seconds??180});
  key.value='';await go('settings');message('LLM 已保存。可提交一条链接验证内容处理。');
 });
 const engines=node('section',null,'engine-grid');engines.setAttribute('aria-label','引擎配置');
 append(engines,model,engineForm(settings,'search','搜索引擎','根据关注内容查找公开资料。'),engineForm(settings,'reader','反爬引擎','获取网页、公众号和视频页面中可读取的内容。'));view.append(engines);
 const optional=node('details',null,'panel form-narrow');optional.append(node('summary','可选：向量检索与重排'));
 optional.append(node('p','向量模型帮助找到表达不同但含义相近的资料；重排模型改善候选排序。未配置时使用关键词检索。索引不会替代原文证据。','hint'));
 for(const [kind,title,path] of [['embedding','向量模型','/v1/embeddings'],['rerank','重排模型','/v1/rerank']]){
  const config=settings.retrieval?.[kind]||{},form=node('form',null,'section-gap');form.dataset.retrieval=kind;
  form.append(node('h2',title));choice(form,'是否启用','enabled',[['false','停用'],['true','启用']],String(Boolean(config.enabled)));
  field(form,'完整接口地址','endpoint',{type:'url',value:config.endpoint||'',hint:'包含接口路径，例如 '+path+'。'});
  field(form,'模型名称','model',{value:config.model||''});
  const secret=field(form,'密钥（如需要）','api_key',{type:'password',hint:config.key_configured?'已保存；同一服务留空保留。':'无需密钥可留空。'});secret.autocomplete='new-password';
  formSubmit(form,'保存'+title,async data=>{await action('settings-retrieval',{kind,endpoint:data.get('endpoint').trim(),model:data.get('model').trim(),api_key:data.get('api_key'),enabled:data.get('enabled')==='true'});secret.value='';await go('settings');message(title+'已保存。向量模型变更后请重建索引。');},false);optional.append(form);
 }
 optional.append(button('重建向量索引',async()=>{const result=await request('/api/v1/retrieval/reindex',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:'{}'});message(result.status==='complete'?'向量索引已重建。':result.message||result.reason||'索引未完成，请检查向量服务。',result.status!=='complete');}));view.append(optional);
 const verify=node('section',null,'panel form-narrow');
 append(verify,node('h2','试一试'),node('p','提交链接验证采集，或输入关键词验证搜索。结果会与配置状态分开记录。','hint'),button('去收件箱提交链接',()=>go('inbox')));
 const search=node('form');field(search,'搜索词','query',{required:true});
 const results=node('div');results.setAttribute('aria-live','polite');
 formSubmit(search,'搜索一次',async data=>{
  results.replaceChildren();const output=await action('search-web',{query:data.get('query'),limit:3});
  if(output.status==='running')return;
  results.append(node('p',output.results?.length?'已取得以下结果：':'搜索没有返回匹配结果。'));
  for(const item of output.results||[])results.append(row(item.title,item.url));
 },false);
 search.className='section-gap';append(verify,search,results);view.append(verify);
}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));
function logout(){clearExport();token='';epoch++;sessionStorage.removeItem('kc-workbench-token');$('#shell').hidden=true;$('#login').hidden=false;$('#token').value='';view.replaceChildren();$('#token').focus();}
$('#logout').addEventListener('click',logout);
$('#connect-form').addEventListener('submit',async event=>{event.preventDefault();const submit=event.submitter;submit.disabled=true;token=$('#token').value.trim();try{await loadOverview();if($('#remember-token').checked)sessionStorage.setItem('kc-workbench-token',token);else sessionStorage.removeItem('kc-workbench-token');$('#token').value='';$('#login-status').textContent='';$('#login').hidden=true;$('#shell').hidden=false;await go('inbox');}catch(error){token='';$('#login-status').textContent=error.message;}finally{submit.disabled=false;}});
if(token){try{await loadOverview();$('#login').hidden=true;$('#shell').hidden=false;await go('inbox');}catch{token='';sessionStorage.removeItem('kc-workbench-token');$('#login-status').textContent='之前的连接已失效，请重新输入令牌。';}}
